### ISSUE TITLE
Validate final board against expected one

### ISSUE THREAD

**Issue by faloi** [uqbar-project/mumuki-gobstones-server#14]
Right now, the "test" is just a gbb file that's used by the runner as the initial board. My proposal is to turn that file into a YAML containing both the initial and the final board and then comparing the expected and actual board in the test runner.

Some considerations:
- the position of the head should not be checked (at least for now, in a future it would be nice to enable that check at will)
- different gbb's can represent the same board because:
  + empty cells can or cannot appear, so a line like `cell 7 2 Azul 0 Negro 0 Rojo 0 Verde 0` doesn't mean anything
  + and the same happens with colors without stones, `cell 7 2 Azul 0 Negro 9 Rojo 0 Verde 0` is equivalent to `cell 7 2 Negro 9`

And some things to work out (with the help of @flbulgarelli):
- the feedback of a passed test could be the initial and the final state of the board. Or should that be the result of the test?
- in the case of a failed test, how can we represent the failure? The easiest thing is to show both the expected and the actual board, and let the users figure out the difference by themselves... but the platform doesn't support an HTML output. Perhaps we should address that issue first.

**Comment by flbulgarelli** [comment]
Regarding your questions, I think we should use output instead of just feedback, and it should be something like  "expected this board, but got that board" - where this and that are just the board's htmls representations. 

And yes, the platform should support html output. We should do something similar to what you already did with feedback, but now, we should add an output format option to the test result.

Or better, let the configuration of feedback and output format be an attribute of the language object. That way, messages exchanged between runner and platform would require less fields.

**Comment by faloi** [comment]
> Regarding your questions, I think we should use output instead of just feedback, and it should be something like "expected this board, but got that board" - where this and that are just the board's htmls representations.

Ok, that is in case of a failure. What about a success?

> And yes, the platform should support html output. We should do something similar to what you already did with feedback, but now, we should add an output format option to the test result.

> Or better, let the configuration of feedback and output format be an attribute of the language object. That way, messages exchanged between runner and platform would require less fields.

We can follow that discussion on uqbar-project/mumuki-platform#164

**Comment by flbulgarelli** [comment]
Here is a suggestion of a test file: https://gist.github.com/flbulgarelli/75da9928ac369c4388ef#file-spec-gbb-yml

**Comment by flbulgarelli** [comment]
> Ok, that is in case of a failure. What about a success?

It is enough with saying "passed", or showing a dot. Actually the output in case of success is not very important. 

Perhaps it would be a good idea to model each test as `(title, input_board, final_board)`. That way the output would be better in case of failure - and in case of success, but, as said, it is not very important for Mumuki right now.

**Comment by faloi** [comment]
Great, so the feedback won't be used for now. For this to work, we need to address uqbar-project/mumuki-platform#165 first
