### ISSUE TITLE
Validate some procedure was called

### ISSUE THREAD

**Issue by faloi** [uqbar-project/mumuki-gobstones-server#19]
A lot of Gobstones guides are designed to be incremental, so the student can start with a tiny problem and proceed to bigger things, reusing the previously defined procedures.

In those cases, you do want to check whether she has used certain procedures.

**Developer notes**
Example output from the gobstones parser (`gbs --print-ast --no-print-board --no-print-retvals`):

```
AST(program
    AST(
        AST(entrypoint
            program
            AST()
            AST(
                AST(procCall
                    Poner
                    AST(
                        AST(literal
                            Rojo)))
                AST(procCall
                    Sacar
                    AST(
                        AST(literal
                            Rojo))))
            None)))
```

**Comment by flbulgarelli** [comment]
Here is a gist of how you could parse inspections and eval them https://gist.github.com/flbulgarelli/9d6e126e8e40bdd10bc9
