### ISSUE TITLE
The error output is bad formatted when it has newlines

### ISSUE THREAD

**Issue by faloi** [uqbar-project/mumuki-gobstones-server#27]
![image](https://cloud.githubusercontent.com/assets/1585835/7891940/0cb7375a-0627-11e5-929c-109f141c31a9.png)

**Comment by flbulgarelli** [comment]
Is it because newlines or because html is not propertly generated when an excepcion occurs?

**Comment by faloi** [comment]
I think that \n's are being ignored

**Comment by faloi** [comment]
An even better hack is to wrap everything with a `<pre>`... I'm doing that now :stuck_out_tongue_winking_eye:
