### ISSUE TITLE
Expectations don't work when the exercise has extra code

### ISSUE THREAD

**Issue by faloi** [uqbar-project/mumuki-gobstones-server#32]
Gobstones' compiler can't generate the AST of an incomplete program, it fails if any procedure is not defined. Right now, the `ExpectationsRunner` only receives the submitted code but not the extra, and therefore the full program is not available and the AST cannot be generated.

@flbulgarelli should we add a new parameter to `ExpectationsRunner#run_expectations!` and invoke the compiler in the runner? or should we pass the compiled code directly from Mumukit? I think the last one could break another runners.

**Comment by flbulgarelli** [comment]
Yes, the second option is not viable since it is not generic enough. It would just add a new paramter as you described.
